### PR TITLE
Server cleanup

### PR DESCRIPTION
**Pull request by WJVincent**
Cleaned up files

### CODE REVIEW

**Review by cosmoscha — COMMENTED** [review]
the refactored code looks cleaner and neater. the biggest changes is to users route

**Review by RamsesRomeroJr — COMMENTED** [review]
everything is looking good to me, we'll just aprove it after the rest of the team checks it out. Also I like the checkPassword function created, makes the route look much cleaner. Also I saw you removed the decoder64, did we never use it?

**Comment by WJVincent** [comment]
> everything is looking good to me, we'll just aprove it after the rest of the team checks it out. Also I like the checkPassword function created, makes the route look much cleaner. Also I saw you removed the decoder64, did we never use it?

As far as I could tell that was an extraneous vscode auto import. I couldn't find anywhere it was being used and I couldn't find anything it affected while testing the routes but I'm not 100% sure.

**Review by andrewscohen — APPROVED** [review]
Well done

**Pull request merged**
